name: LinuxRelease_aarch64

on:
  schedule:
    # Run weekly on Monday 00:00
    - cron:  '00 00 * * MON'
  push:
    branches: [master, rel-*]
  pull_request:
    branches: [rel-*]
  #workflow_dispatch:

jobs:
  build:
    #if: github.event_name != 'pull_request' || startsWith( github.base_ref, 'rel-') || contains( github.event.pull_request.labels.*.name, 'run release CIs')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [cp37-cp37m, cp38-cp38, cp39-cp39]
        arch: ['aarch64']
    env:
      py: /opt/python/${{ matrix.python-version }}/bin/python
      img: quay.io/pypa/manylinux2014_${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Install dependencies
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc '\
          ${{ env.py }} -m pip install -U numpy protobuf==3.11.3 && \
          yum install -y protobuf-compiler protobuf-devel'        
          
    - name: Build manylinux2014_aarch64
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc '\
          yum install -y sudo && \
          sudo chmod +x .github/workflows/manylinux/entrypoint.sh && \
          sudo .github/workflows/manylinux/entrypoint.sh ${{ env.py }} manylinux2014_aarch64 ${{ github.event_name }}'

    - name: Test wheel with Python ${{ matrix.python-version }}
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc '${{ env.py }} -m pip install virtualenv && ${{ env.py }} -m venv .env && \
          source .env/bin/activate && \
          python -m pip install --upgrade pip && \
          pip install dist/*manylinux2014_aarch64.whl && \
          pip install pytest nbval ipython==7.16.1 && \
          pytest && \
          deactivate'
          
    - name: Test backend test data
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc '${{ env.py }} -m pip install virtualenv && ${{ env.py }} -m venv .env && \
          source .env/bin/activate && \
          # onnx.checker all existing backend data
          python workflow_scripts/test_generated_backend.py && \
          # onnx.checker all generated backend data && \
          python onnx/backend/test/cmd_tools.py generate-data && \
          python workflow_scripts/test_generated_backend.py && \
          deactivate'
          
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: dist

    - name: Upload wheel to TestPyPI weekly
      if: (github.event_name == 'schedule') # Only triggered by weekly event
      run: |
        python -m pip install -q twine
        twine upload --verbose dist/*.whl --repository-url https://test.pypi.org/legacy/ -u ${{ secrets.TESTPYPI_USERNAME }} -p ${{ secrets.TESTPYPI_PASSWORD }}
        
    - name: Verify ONNX with the latest numpy
      if: ${{ always() }}
      run: |
         docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc '${{ env.py }} -m pip install virtualenv && ${{ env.py }} -m venv .env && \
          source .env/bin/activate && \
          python -m pip uninstall -y numpy onnx && python -m pip install numpy && \
          python -m pip install dist/*manylinux2014_aarch64.whl && \
          python -m pip install pytest && \
          pytest && \
          deactivate'
        
    - name: Verify ONNX with the latest protobuf
      if: ${{ always() }}
      run: |
         docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc '${{ env.py }} -m pip install virtualenv && ${{ env.py }} -m venv .env && \
          source .env/bin/activate && \
          python -m pip uninstall -y protobuf onnx && python -m pip install protobuf && \
          python -m pip install dist/*manylinux2014_aarch64.whl && \
          python -m pip install pytest && \
          pytest && \
          deactivate'
        
    - name: Verify ONNX with ort-nightly
      if: ${{ always() }}
      run: |
         docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc '${{ env.py }} -m pip install virtualenv && ${{ env.py }} -m venv .env && \
          source .env/bin/activate && \
          python -m pip install flatbuffers && \
          python -m pip install -i https://test.pypi.org/simple/ ort-nightly && \
          python onnx/test/test_with_ort.py && \
          deactivate'

